### ISSUE TITLE
Scope starts with by rank and/or known parent

### ISSUE THREAD

**Issue by ermbutler** [fathomnet/worms-server#4]
I am using the following endpoint for an autocomplete:
https://fathomnet.org/worms/taxa/query/startswith

To allow for scoped results, we were wondering if these two options could be considered:

By rank:
- https://fathomnet.org/worms/taxa/query/startswith/{term}?rank={rank}
- ie. worms/taxa/query/startswith/str?rank=Family

Within a descendent of a parent:
- https://fathomnet.org/worms/taxa/query/startswith/{term}?parent={parent}
- ie. worms/taxa/query/startswith/str?parent=Asteroidea

Combination:
- ie. worms/taxa/query/startswith/str?parent=Asteroidea&rank=Species

**Comment by hohonuuli** [comment]
@ermbutler This should be done now. Let me know if you run into any issues. 


### Test URLs for your examples

>  worms/taxa/query/startswith/str?rank=Family

<https://fathomnet.org/worms/taxa/query/startswith/or?rank=family>

> worms/taxa/query/startswith/str?parent=Asteroidea

<https://fathomnet.org/worms/taxa/query/startswith/or?parent=Asteroidea>

> worms/taxa/query/startswith/str?parent=Asteroidea&rank=Species

<https://fathomnet.org/worms/taxa/query/startswith/or?parent=Asteroidea&rank=species>

# Other tests
- <https://fathomnet.org/worms/taxa/query/startswith/shrimp?rank=species>
- <https://fathomnet.org/worms/taxa/query/startswith/blue?parent=Hydrozoa&rank=species>
- <https://fathomnet.org/worms/taxa/query/startswith/Wyv?rank=genus>

**Comment by hohonuuli** [comment]
Notes:
- `parent` really means _ancestor_. I'll leave as-is as it's easier for end users to spell 😜 
- The parent is case sensitive. 
- `rank` is case insensitive.

**Comment by hohonuuli** [comment]
Released in v0.4.5

**Comment by ermbutler** [comment]
Thanks @hohonuuli, Appreciate the update! I am going to play with this now.

The current use case should be ok with the case sensitive parent, but I will let you know if that ends up tripping me up.
